baseURL = "/"
languageCode = "en-us"
title = "Digital Tea House"
theme = "parsa"
summaryLength = "10"

[outputs]
home = ["HTML", "RSS", "JSON"]
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


[params]

logo = "/DTHLOGO.PNG"
description = "Digital Tea House : ကျုပ်တို့  ရဲ့ လက်ဘက်ရည်ဆိုင် 'Digital Tea House'  က ပုံမှန်လက်ဘက်ရည်ဆိုင်မဟုတ်ဘူးဗျ။ ဒစ်ဂျစ်တယ်လက်ဘက်ရည်ဆိုင် ။"
home = "Home"
layout = "1"

[[menu.main]]
name = "ပင်မစာမျက်နှာ"
weight = 1
URL = "/"

[[menu.main]]
name = "ဒစ်ဂျစ်တယ်ဖတ်စရာများ"
weight = 2 
URL = "articles"

[[menu.main]]
name = "စာအုပ်စင်"
weight = 3
URL = "materials"
[[menu.main]]
name = "ဒစ်ဂျစ်တယ်ရေဒီယို"
weight = 4
URL = "radio"

[[menu.main]]
name = "လဖက်ရည်ဆိုင်အကြောင်း"
weight = 5
URL = "about"



[params.preloader]
enable = true